services:
  - type: web
    name: render-server
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    healthCheckPath: /health

    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: MONGO_URI
        sync: false
